### ISSUE TITLE
Binding DNS port 53 on the host

### ISSUE THREAD

**Issue by tmichaud314** [hashicorp/docker-consul#26]
I use the Docker image from Gliderlabs and would like to replace it with Hashicorp's image.  But ran into an issue when running a consul:v0.6.4 container in "host" network-mode and binding the Consul DNS server to port 53.  This works for the Gliderlab's image because consul agent is run as 'root'.

It would be great if there was an option to override Hashicorp consul's default user and group settings ( consul:consul) by setting an environment variable.  Something like:

`docker run -itd consul:v0.6.4 -e CONSUL_USER=root -e CONSUL_GROUP=root ...`

It might be better to limit the option to the 'root' user or group because that is the only other user/group guaranteed to exist in the container.

wdyt?

**Comment by slackpad** [comment]
Hi @tmichaud314 I'd like to avoid running Consul as root - it's not a good practice since it can run scripts of various types and even arbitrary scripts via `consul exec`.

Please take a look at https://github.com/hashicorp/docker-consul/issues/15 which has some discussion around port 53 and some ideas for fixing it without running as root. I'll close this as a duplicate.
